#!/usr/bin/env node
/**
 * Builds the local NetEase API bridge into one self-contained executable.
 *
 * Why this is not a one-line esbuild call: `NeteaseCloudMusicApi` enumerates its
 * 377 route modules by calling `fs.readdirSync(path.join(__dirname, 'module'))`
 * and then `require()`-ing each file. Neither the directory nor the files exist
 * inside a Node Single Executable Application, so the build:
 *
 *   1. generates `virtual-modules.cjs`, which maps every route-module file name
 *      to a statically bundled copy and patches `fs.readdirSync`,
 *      `fs.promises.readdir` and `Module._load` to answer from that map,
 *   2. generates an entry that requires the patch *before* the library, so the
 *      redirect is installed by the time the library enumerates its modules,
 *   3. bundles both into `ncm-api.cjs` and embeds it as a SEA asset.
 *
 * The base runtime is the *official* prebuilt Node rather than the distribution
 * one: Arch's `node` has an ELF layout that postject corrupts (the result dumps
 * core on start), while the upstream build injects cleanly.
 *
 * Output: sidecar/dist/yunyin-api-<target-triple> - the name Tauri's
 * `externalBin` expects.
 */

import { execFileSync, spawn } from 'node:child_process'
import {
  chmodSync,
  copyFileSync,
  createWriteStream,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { get } from 'node:https'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SIDECAR = path.join(ROOT, 'sidecar')
const DIST = path.join(SIDECAR, 'dist')
const CACHE = path.join(SIDECAR, '.cache')
const LIB = path.join(SIDECAR, 'node_modules', 'NeteaseCloudMusicApi')
const ESBUILD = path.join(ROOT, 'node_modules', '@esbuild', 'linux-x64', 'bin', 'esbuild')
const POSTJECT = path.join(ROOT, 'node_modules', '.bin', 'postject')

/** Node release used as the SEA base. Pinned for reproducible builds. */
const NODE_VERSION = process.env.YUNYIN_NODE_VERSION || 'v24.10.0'

function targetTriple() {
  const arch =
    process.arch === 'x64' ? 'x86_64' : process.arch === 'arm64' ? 'aarch64' : process.arch
  return arch + '-unknown-linux-gnu'
}

function run(command, args) {
  execFileSync(command, args, { stdio: 'inherit', cwd: ROOT })
}

function download(url, destination) {
  return new Promise((resolve, reject) => {
    const request = get(url, { headers: { 'User-Agent': 'yunyin-build' } }, (response) => {
      if (response.statusCode === 301 || response.statusCode === 302) {
        download(response.headers.location, destination).then(resolve, reject)
        return
      }
      if (response.statusCode !== 200) {
        reject(new Error('download failed ' + url + ': HTTP ' + response.statusCode))
        return
      }
      const file = createWriteStream(destination)
      response.pipe(file)
      file.on('finish', () => file.close(() => resolve()))
      file.on('error', reject)
    })
    request.on('error', reject)
  })
}

async function ensureNodeRuntime() {
  const arch = process.arch === 'x64' ? 'x64' : process.arch === 'arm64' ? 'arm64' : process.arch
  const name = 'node-' + NODE_VERSION + '-linux-' + arch
  const runtime = path.join(CACHE, name, 'bin', 'node')
  if (existsSync(runtime)) {
    console.log('[sidecar] using cached runtime ' + NODE_VERSION)
    return runtime
  }

  mkdirSync(CACHE, { recursive: true })
  const tarball = path.join(CACHE, name + '.tar.xz')
  if (!existsSync(tarball) || statSync(tarball).size < 1_000_000) {
    const url = 'https://nodejs.org/dist/' + NODE_VERSION + '/' + name + '.tar.xz'
    console.log('[sidecar] downloading ' + url)
    await download(url, tarball)
  }
  console.log('[sidecar] extracting the Node runtime...')
  run('tar', ['-xf', tarball, '-C', CACHE])
  if (!existsSync(runtime)) throw new Error('extracted runtime missing: ' + runtime)
  return runtime
}

/** Writes the redirect shim plus the entry that installs it before the library. */
function generateVirtualModules(moduleDir, names) {
  const requires = names
    .map(
      (name) =>
        '  ' +
        JSON.stringify(name) +
        ': () => require(' +
        JSON.stringify(path.join(moduleDir, name)) +
        '),',
    )
    .join('\n')

  const shim = path.join(DIST, 'virtual-modules.cjs')
  writeFileSync(
    shim,
    `// GENERATED by scripts/build-sidecar.mjs - do not edit.
//
// Serves the library's route-module directory from statically bundled copies,
// so the directory scan and the requires it performs at import time never touch
// a file system (which a Single Executable Application does not have).
const fs = require('node:fs')
const Module = require('node:module')

const MODULE_FILES = ${JSON.stringify(names)}

/** True for any path that points into a route-module directory. */
function isModulePath(value) {
  if (typeof value !== 'string') return false
  const normalised = value.split('\\\\').join('/')
  return normalised.includes('/module/') || normalised.endsWith('/module')
}

/** file name -> loader for the bundled copy of that route module. */
const loaders = {
${requires}
}

function loaderFor(value) {
  const parts = String(value).split('\\\\').join('/').split('/')
  const name = parts[parts.length - 1]
  return name ? loaders[name] : undefined
}

const originalReaddirSync = fs.readdirSync
fs.readdirSync = function readdirSync(target, ...rest) {
  if (isModulePath(target)) return MODULE_FILES.slice()
  return originalReaddirSync.apply(this, [target, ...rest])
}

const originalReaddir = fs.promises.readdir.bind(fs.promises)
fs.promises.readdir = function readdir(target, ...rest) {
  if (isModulePath(target)) return Promise.resolve(MODULE_FILES.slice())
  return originalReaddir(target, ...rest)
}

const originalResolve = Module._resolveFilename
Module._resolveFilename = function resolveFilename(request, parent, ...rest) {
  if (isModulePath(request) && loaderFor(request)) return request
  return originalResolve.apply(this, [request, parent, ...rest])
}

const originalLoad = Module._load
Module._load = function load(request, parent, isMain) {
  if (isModulePath(request)) {
    const loader = loaderFor(request)
    if (loader) return loader()
  }
  return originalLoad.apply(this, [request, parent, isMain])
}

module.exports = { MODULE_FILES }
`,
  )

  const entry = path.join(DIST, 'library-entry.cjs')
  writeFileSync(
    entry,
    `// GENERATED by scripts/build-sidecar.mjs - do not edit.
// Install the route-module redirect first, then load the library.
require(${JSON.stringify(shim)})
module.exports = require(${JSON.stringify(path.join(LIB, 'main.js'))})
`,
  )

  return entry
}

function bundleLibrary() {
  const moduleDir = path.join(LIB, 'module')
  const names = readdirSync(moduleDir)
    .filter((name) => name.endsWith('.js'))
    .sort()
  if (!names.length) throw new Error('no route modules found in ' + moduleDir)

  const entry = generateVirtualModules(moduleDir, names)
  const outfile = path.join(DIST, 'ncm-api.cjs')
  run(ESBUILD, [
    entry,
    '--bundle',
    '--platform=node',
    '--format=cjs',
    '--target=node22',
    '--outfile=' + outfile,
    '--external:node:*',
    '--log-level=warning',
  ])
  console.log('[sidecar] bundled ' + names.length + ' route modules')
  return outfile
}

function bundleBridge() {
  const outfile = path.join(DIST, 'yunyin-api.cjs')
  run(ESBUILD, [
    path.join(SIDECAR, 'server.mjs'),
    '--bundle',
    '--platform=node',
    '--format=cjs',
    '--target=node22',
    '--outfile=' + outfile,
    '--external:node:*',
    '--external:NeteaseCloudMusicApi*',
    '--log-level=warning',
  ])
  return outfile
}

async function smokeTest(outfile) {
  const port = 39000 + Math.floor(Math.random() * 900)
  const child = spawn(outfile, ['--port', String(port)], { stdio: ['ignore', 'pipe', 'pipe'] })
  let stderr = ''
  child.stderr.on('data', (chunk) => {
    stderr += String(chunk)
  })

  const started = await new Promise((resolve) => {
    const deadline = Date.now() + 30_000
    const check = async () => {
      try {
        const response = await fetch('http://127.0.0.1:' + port + '/health')
        if (response.ok) return resolve(true)
      } catch {
        /* not up yet */
      }
      if (Date.now() > deadline) return resolve(false)
      setTimeout(check, 400)
    }
    void check()
  })

  if (!started) {
    child.kill('SIGKILL')
    throw new Error('executable did not start. stderr:\n' + stderr.slice(0, 2000))
  }

  // Exercise routes that depend on the virtual module table. Upstream flakiness
  // (NetEase rate limits and 502s) must not fail the build, so each probe is
  // retried and a 5xx from upstream is reported rather than thrown.
  try {
    const probes = ['/search?keywords=test&limit=1', '/personalized?limit=1', '/toplist']
    for (const route of probes) {
      let result = null
      for (let attempt = 0; attempt < 3; attempt += 1) {
        const response = await fetch('http://127.0.0.1:' + port + route)
        const body = await response.json()
        result = body
        if (typeof body.code !== 'number' || body.code === 200 || body.code === 0) break
        // A 404/501 here would mean the route is not wired up correctly.
        if (body.code === 404 || body.code === 501) {
          throw new Error(route + ' is not wired up (code=' + body.code + ')')
        }
        await new Promise((resolve) => setTimeout(resolve, 800))
      }
      if (typeof result?.code === 'number' && result.code >= 500) {
        console.log('[sidecar] note: ' + route + ' returned upstream code=' + result.code)
      }
    }
  } finally {
    child.kill('SIGTERM')
  }
  console.log('[sidecar] smoke test passed (routes wired, upstream reachable)')
}

async function main() {
  if (!existsSync(path.join(LIB, 'package.json'))) {
    throw new Error(
      'missing sidecar/node_modules/NeteaseCloudMusicApi - run npm install in sidecar/ first',
    )
  }
  mkdirSync(DIST, { recursive: true })

  const library = bundleLibrary()
  const bridge = bundleBridge()
  const runtime = await ensureNodeRuntime()

  const blob = path.join(DIST, 'yunyin-api.blob')
  const seaConfig = path.join(DIST, 'sea-config.json')
  writeFileSync(
    seaConfig,
    JSON.stringify(
      {
        main: bridge,
        output: blob,
        disableExperimentalSEAWarning: true,
        useSnapshot: false,
        useCodeCache: false,
        assets: { 'ncm-api.cjs': library },
      },
      null,
      2,
    ),
  )

  console.log('[sidecar] generating the SEA blob...')
  run(runtime, ['--experimental-sea-config', seaConfig])

  const outfile = path.join(DIST, 'yunyin-api-' + targetTriple())
  rmSync(outfile, { force: true })
  copyFileSync(runtime, outfile)
  chmodSync(outfile, 0o755)

  console.log('[sidecar] injecting the blob into the Node runtime...')
  run(POSTJECT, [
    outfile,
    'NODE_SEA_BLOB',
    blob,
    '--sentinel-fuse',
    'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
  ])

  rmSync(blob, { force: true })
  rmSync(seaConfig, { force: true })

  const size = (readFileSync(outfile).length / 1024 / 1024).toFixed(1)
  console.log('[sidecar] built ' + path.relative(ROOT, outfile) + ' (' + size + ' MB)')
  await smokeTest(outfile)
}

main().catch((error) => {
  console.error('[sidecar] build failed: ' + error.message)
  process.exit(1)
})
